---
- hosts: elasticsearch-servers
  pre_tasks:
    - raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3-minimal)
  become: true
  roles:
    - common
    - combine-elasticsearch
