---
- hosts: spark-servers
  pre_tasks:
    - raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3-minimal)
  become: true
  roles:
    - common
    - java
    - spark
    - ingestion3
    - livy
    - hadoop
    - supervisor
